### ISSUE TITLE
Enable library for Linux on Z (s390x)

### ISSUE THREAD

**Issue by edelsohn** [mirage/mirage-crypto#128]
Add support for Linux on IBMz (s390x) 64-bit architecture.

ISA:
https://linux.mainframe.blog/zarchitecture-principles-of-operation/

Free access to Linux on Z VM:
https://linuxone.cloud.marist.edu/#/register?flag=VM

**Comment by avsm** [comment]
We won't be adding support to a crypto library for something we cannot ensure the quality of on an ongoing basis. @edelsohn, would you mind emailing me on anil@recoil.org about this request? We need access to a reasonable number of Z cores (not the tiny free plan) in order to to end-to-end package builds.

When I enquired last year, I was emailed by meredith.stowell@us.ibm.com on 2nd Dec 2020 who said:
> We have a number of options to access s390x systems for academic, research, and open source community projects. Let me pull a few of our technical resources together to better understand your project and requirements so we can look at various options. I will get back to you to schedule a call once I have identified the colleagues to include.

And then she stopped responding altogether despite multiple emails from me.

I don't have the capacity to chase up anyone through the IBM organisation. If you have someone else who could get us access to a stable, and reasonable number of cores to do bulk package builds, then we can support Z. By comparison, we have ~1000 cores in our x86 build pool, and ~400 in our arm64 pool, and ~160 in our ppc64le pool.

**Comment by edelsohn** [comment]
Are the numbers of "cores" referring to hardware threads or to processor cores? I suspect that they refer to hardware threads as shown by Linux /proc/cpuinfo.  There is a big difference.

Also, s390x systems have different performance characteristics from other systems, so forecasting resource requirements based on x86 systems is not accurate.  Starting a conversation with "we want 100's or 1000's of s390x cores" is not productive.

**Comment by edelsohn** [comment]
I'm happy to work with the OCaml community to provide long-term access to Linux on s390x systems. I sent you private email.

**Comment by avsm** [comment]
Update: I've got a VM now and am getting the base image builder hooked up. A manual run has succeeded with OCaml 4.12 images, so it should be straightforward.

**Comment by hannesm** [comment]
thanks for your issue, and your pull request that I just merged. I opened a new issue, #131 with further s390x improvements.
