### ISSUE TITLE
remove logs dependency?

### ISSUE THREAD

**Issue by copy** [mirage/mirage-crypto#240]
Logs is used in the `initialize` function in the various os-specific rng generators (as well as [mirage/unikernel.ml](https://github.com/mirage/mirage-crypto/blob/4204d9d2b2e3b5d66c16b7d6833f540d7e0fe956/mirage/unikernel.ml#L3)): https://github.com/search?q=repo%3Amirage%2Fmirage-crypto+log.&type=code

I wonder if `initialize` could be changed to return ``(unit, [> `Already_initialized]) result``, and the logs dependency could be removed.

The main advantage would be that logs is the only non-dune dependency, and we wouldn't have to use opam-overlays or pins in projects using [opam-monorepo](https://github.com/tarides/opam-monorepo).

**Comment by hannesm** [comment]
Changing the initialize function is a pain, since it needs to be updated for all users. Now, what should a return value of `` `Already_initialized `` lead to? Ignoring it? Logging it?

I don't think it is worth to bother removing it. The common use is via opam, and there is no need to bother about the build system. Now if you're in a dune-only setting, let me know which logging library you're using. For MirageOS we decided years ago that `logs` is the logging library of choice, and I'm ery happy with it.

opam-monorepo can indeed be very painful. Fortunately there's the promise that "dune pkg management" will be different and not suffer from the same issues as opam-monorepo. For reasons unknown to me, the dune pkg stuff is delayed quite a bit (if I remember correctly, their first MVC was planned for beginning of 2024, now it is the second half of 2024 and I don't know what their schedule is).

**Comment by copy** [comment]
> Changing the initialize function is a pain, since it needs to be updated for all users.

I guess this issue has a bad timing, considering 1.0 was just released.

> Now, what should a return value of `Already_initialized lead to? Ignoring it? Logging it?

I'd write `if Result.is_error (Mirage_crypto_rng_unix.initialize (...)) then failwith "Mirage_crypto_rng_unix.initialize failed"`, but ignoring or logging are also fine choices.

I also consider ignoring or raising as a reasonable choice for the library (and keeping the existing signature).

> Now if you're in a dune-only setting, let me know which logging library you're using.

I tend to roll my own one-liner (`let log fmt = Printf.printf (fmt ^^ "\n%!")`) and extend it as needed, but I understand mirage has different needs.

**Comment by hannesm** [comment]
I'll close this issue as wontfix.
